server:
  port: 9040

spring:
  application:
    name: navita-parking
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5433/db-navita-parking
    username: navita
    password: navita
eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
